dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable
# addons:
#    chrome: stable
  # apt:
  #   sources:
  #     - google-chrome
  #   packages:
  #     - google-chrome-stable

cache:
  npm: false

install:
  - npm install

before_script:
  - cd 01_Web_Portal
  - npm install
 
script:
   - npm run build
